//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPIMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        public int BusinessId { get; set; }
        public string Street { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public int StateId { get; set; }
        public string Zip { get; set; }
        public Nullable<long> CensusPopulation { get; set; }
        public Nullable<int> CensusYear { get; set; }
        public byte[] Map { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string CreatedBy { get; set; }
    
        public virtual Business Business { get; set; }
    }
}
