//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPIMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Business
    {
        public int BusinessId { get; set; }
        public string BusinessName { get; set; }
        public string BusinessType { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string CreatedBy { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual Identity Identity { get; set; }
        public virtual Job Job { get; set; }
        public virtual Lender Lender { get; set; }
    }
}
