//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPIMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lender
    {
        public int BusinessId { get; set; }
        public string NAICSCode { get; set; }
        public string LenderName { get; set; }
        public string CD { get; set; }
        public System.DateTime DateApproved { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string CreatedBy { get; set; }
    
        public virtual Business Business { get; set; }
    }
}
