//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPIMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class State
    {
        public int StateId { get; set; }
        public string Name { get; set; }
        public string Abbreviation { get; set; }
        public Nullable<int> RegionIdFK { get; set; }
        public Nullable<int> DivisionIdFK { get; set; }
    
        public virtual Division Division { get; set; }
        public virtual Region Region { get; set; }
    }
}
